const TAMANHO_DA_PISTA = 10000

const TEMPO_DE_RESPOSTA = 10 // Segundos

const VELOCIDADE_GANHA_POR_ACERTO = 1
const VELOCIDADE_PERDIDA_POR_ERRO = 1

const VEICULO_OFFSET = 10
const VEICULO_ESPACAMENTO = 75

const PISTA_OFFSET = 0
const PISTA_ALTURA = 75

const SINALEIRA_TEMPO_MUDAR_COR = 1 // Segundos
const SINALEIRA_FIM_DELAY = 1000 // Milisegundos para começar o jogo após o sinal verde

const MULTIPLICADOR_SCORE = 1

// Quantidade de últimas partidas mostradas no placar
const HISTORIA_MAX_PLACAR = 3

export {TAMANHO_DA_PISTA, TEMPO_DE_RESPOSTA, VELOCIDADE_GANHA_POR_ACERTO, VELOCIDADE_PERDIDA_POR_ERRO, VEICULO_OFFSET, VEICULO_ESPACAMENTO, PISTA_OFFSET, PISTA_ALTURA, SINALEIRA_TEMPO_MUDAR_COR, SINALEIRA_FIM_DELAY, MULTIPLICADOR_SCORE, HISTORIA_MAX_PLACAR}
